### ISSUE TITLE
update copyright headers

### ISSUE THREAD

**Issue by petibub** [sofacoustics/SOFAtoolbox#50]
1) make sure that the order is authors --> boilerplate
2) make sure that the correct function is in the header
3) remove the year
4) change the boilerplate from GPL to EUPL in files we have permission from the owner to change the license

**Comment by isfmiho** [comment]
> 3. remove the year

--> In which part? In the #author rows?

**Comment by petibub** [comment]
In the line with the copyright message. If it makes sense for you, of course...

**Comment by isfmiho** [comment]
agree; 
--> fixed
