### ISSUE TITLE
upgrade for MultiSpeakerBRIR

### ISSUE THREAD

**Issue by petibub** [sofacoustics/SOFAtoolbox#59]
Implement in SOFAupgradeConventions() an automatic upgrade of MultiSpeakerBRIR files to SingleRoomSRIR. 

Example for such a file: http://sofacoustics.org/data/database/sbsbrir/SBSBRIR_x-0pt5y-0pt5.sofa or http://sofacoustics.org/data/database/thk/BRIR_CR1_KU_MICS_L.sofa

**Comment by f-brinkmann** [comment]
@petibub MultispeakerBRIR uses the FIRE data type and SingleRoomSRIR uses FIR. I don't see how the upgrade can work and would suggest to upgrade to SingleRoomMIMOSRIR instead.

**Comment by isfmiho** [comment]
Thank you; I updated the recommendation on sofaconventions.org.

The automatic upgrade will follow with its milestone.

**Comment by isfmiho** [comment]
In https://github.com/sofacoustics/SOFAtoolbox/tree/master/SOFAtoolbox/test you can find a converter function doing so.

Should it be implemented in SOFAupgradeConventions() and run by default?

**Comment by petibub** [comment]
Yes, that would be great, i.e., I start SOFAupgradeConventions with the deprecated MultiSpeakerBRIR dataset and SOFAupgradeConventions outputs a valid SingleRoomSRIR dataset.

**Comment by isfmiho** [comment]
Implemented in SOFA Toolbox v2.1.5 (development branch).

Keep in mind that the function _SOFAupgradeConventions()_ is not called during _SOFAload_ and _SOFAsave_ by default.
