### ISSUE TITLE
upgrade for SingleRoomDRIR

### ISSUE THREAD

**Issue by petibub** [sofacoustics/SOFAtoolbox#60]
Implement in SOFAupgradeConventions() an automatic upgrade of SingleRoomDRIR files to SingleRoomSRIR.

Example for such a file: http://sofacoustics.org/data/database/thk/DRIR_CR1_VSA_50RS_L.sofa

**Comment by isfmiho** [comment]
In https://github.com/sofacoustics/SOFAtoolbox/tree/master/SOFAtoolbox/test you can find a converter function doing so.

Should it be implemented in SOFAupgradeConventions() and run by default?

**Comment by petibub** [comment]
Yes, that would be great, i.e., I start SOFAupgradeConventions with the deprecated SingleRoomDRIR and obtain a valid dataset with SingleRoomSRIR...

**Comment by petibub** [comment]
Yes, that would be great, i.e., I start SOFAupgradeConventions with the deprecated SingleRoomDRIR dataset and SOFAupgradeConventions outputs a valid SingleRoomSRIR dataset.

**Comment by isfmiho** [comment]
Implemented in SOFA Toolbox v2.1.5 (development branch).

Keep in mind that the function _SOFAupgradeConventions()_ is not called during _SOFAload_ and _SOFAsave_ by default.
