### ISSUE TITLE
General_FIRE 1.0

### ISSUE THREAD

**Issue by f-brinkmann** [sofacoustics/SOFAtoolbox#62]
General_FIRE 1.0 is deprecated according to [sofaconventions.org](https://www.sofaconventions.org/mediawiki/index.php/SOFA_conventions) and https://www.sofaconventions.org/conventions/ but contained in the current SOFAtoolbox release. Is this intended?

**Comment by isfmiho** [comment]
No, this was not on purpose. Thanks for the hint -> Now the convention file is removed from the current development branch and will be removed in future releases.
