### ISSUE TITLE
Two versions of FreeFieldDirectivityTF (1.0 and 1.1) 

### ISSUE THREAD

**Issue by david-ackermann** [sofacoustics/SOFAtoolbox#67]
There are two versions of the FreeFieldDirectivityTF convention in the current master, version 1.0 is probably deprecated? @petibub @f-brinkmann @isfmiho

**Comment by isfmiho** [comment]
Thank you David. I removed the deprecated 1.0 version from the development branch. 
The master branches are updated with official releases. -> The next master release should be correct with the next official release.

**Comment by f-brinkmann** [comment]
Also thanks for noting. @isfmiho can you also move the convention to https://www.sofaconventions.org/conventions/deprecated/ ?

**Comment by isfmiho** [comment]
> Also thanks for noting. @isfmiho can you also move the convention to https://www.sofaconventions.org/conventions/deprecated/ ?

done
