### ISSUE TITLE
SOFAcalculateITD: do not add Delay variable to input data in case of input data is a simple matrix

### ISSUE THREAD

**Issue by micgrzyw** [sofacoustics/SOFAtoolbox#72]
calculateITD raises error in line 320 if input data Obj is a simple matrix (not an SOFA struct)

Could you add the below fix to the code?
![image](https://user-images.githubusercontent.com/93912684/233112785-69240a72-d85d-46a8-9521-d5ad6b35ae81.png)

**Comment by petibub** [comment]
Dear Michal, thanks for the pointer, issue fixed in the development branch.
