### ISSUE TITLE
Deprecate FreeFieldDirectivityTF_1.0.csv

### ISSUE THREAD

**Issue by f-brinkmann** [sofacoustics/SOFAtoolbox#77]
You could already deprecate FreeFieldDirectivityTF_1.0.csv in https://github.com/sofacoustics/SOFAtoolbox/tree/development to make sure its not overlooked at release time.

**Comment by isfmiho** [comment]
Actually it is not included in the latest release version. There is only version 1.1:
https://github.com/sofacoustics/SOFAtoolbox/tree/development/SOFAtoolbox/conventions

**Comment by f-brinkmann** [comment]
Ups sorry - I had an error in my function checking the available conventions. Sorry for the noise...
