### ISSUE TITLE
Questions about Audio as DataType

### ISSUE THREAD

**Issue by f-brinkmann** [sofacoustics/SOFAtoolbox#79]
The new *AnnotaedAudio* conventions introduce the new data type *Audio*, which made me wonder about two things

 - Do we need this, or could it be FIR as well?
 - If we need it, is *Audio* the best name? A FIR is also audio. *Recording* might be more precise.

**Comment by isfmiho** [comment]
_Recording_ has the disadvantage that it might not fit in any cases. If you modify a signal on your computer and play it via headphones or loudspeakers,and also store that output on a computer, it does not need to be an actual recording.
Whereas _Audio_ does also include audio recordings.
Maybe we can talk about the naming...

**Comment by petibub** [comment]
I agree with Michael. Recording would be a too specific type of audio.
By Audio, we mean an audio signal, one could feed to a sound interface. 
While an impulse response can also be sent to a soubd card, it's not its primary application.
We could go for Signal, but we need to distinguish between the much faster sampled audio signal and the much slowlier sampled tracking signals. So, we ended up at Audio.

Does that help?
