### ISSUE TITLE
Missing definition for dimension `R` in (deprecated) TrackedAudio conventions

### ISSUE THREAD

**Issue by f-brinkmann** [sofacoustics/SOFAtoolbox#80]
- Dimension `R` is not defined, i.e., the letter `r` does not appear anywhere in a dimensions field.
- Do we need to keep this deprecated conventions? I wondered if a single sofa file was published using them. If not it might be worth discarding them completely.

**Comment by isfmiho** [comment]
No, the convention was presented during talks, this is why we created the tables as well.
But as far as I know no actual data have been created.
I have no issues discarding it... we'll talk about it.

**Comment by f-brinkmann** [comment]
This convention will remain as deprecated. We decided that conventions with versions <1.0 wont't be checked by consistency by default.
